env:
  browser: true
  es6: true
  node: true

extends: eslint:recommended

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  ecmaVersion: 2017
  sourceType: module
rules:
  array-bracket-spacing:
    - 2
    - never
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
